### ISSUE TITLE
Add JCS as canonicalization scheme

### ISSUE THREAD

**Issue by msporny** [w3c/vc-di-eddsa#25]
The RCH WG is [considering a suggestion](https://w3c.github.io/rdf-canon/spec/#formal-verification-incomplete) that implementers should have backup strategies in case any given canonicalization scheme fails. We should probably provide at least one EdDSA cryptosuite that uses JCS instead of URDNA2015.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-09-15-vcwg#section1-1) on 2022-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Canonicalization schemes.

**Michael Jones:** I queued for the suggestion that maybe we support multiple canonicalization.  
… "Standards is the process of making the choices that don't matter".  
… Do you call things XYZ or PDQ? It often doesn't matter EXCEPT that there is agreement.  
… If there are choices, different developers will make different choices and that harms interop.  

_See github issue [vc-di-eddsa#25](https://github.com/w3c/vc-di-eddsa/issues/25)._




**Michael Jones:** First and foremost, decide.  

**Michael Prorock:** There's a thread about X.509 where choices were allowed and now there is chaos..  
… I am an acknowledged horrible editor on this spec..  
… Because the spec itself bothers me..  
… I brough this up when we first looked at x.509 stuff coming in.  
… There exist already defined stuff. I am concerned at the root level that perhaps we merge JCS2020 merged with the spec.  
… with VC-JWT (make sure it works). That might be a different path..  
… At this point, I don't know how to make it something I would want to continue to work on and implement. That concerns me..  
… Instead of working on product, go do this complicated thing. And I'm familiar with the work.  
… yes we can go to CR, but maybe we should simplify first.  
… Maybe that's a later step, but it feels like we keep kicking the can down the road.  
… Do I think there are practical things we can do? Yes. Pick one..  
… Proofchains: nice to see..  
… Others seem mostly simple..  
… But this meta thing: we never resolved possibly being bound to the IANA jose, so let's not use it in DI.  

**Brent Zundel:** What's the status of JCS.  

> *Ivan Herman:* the question is: how stable is JCS?.

**Michael Jones:** its conditional RFC. Personal submission because JSON working group didn't like it.  
… its informational.  

**Orie Steele:** with DI Proofs, there is a set of things that when you create it, you must do, including defining canonicalization.  
… I've created a lot of DI suites over the year..  
… Every time you create one you HAVE to state the canonicalization.  
… most have been URDNA, but some have been JCS.  
… To say you MUST define the canonicalization, but only show URDNA, that's a problem.  
… We have 90% URDNA..  
… to me the extensibility is better supported by actually supporting JCS as proof of choice.  
… If we only give one example, it's essentially not giving people a choice.  
… We should either support extensibility with a second option, or get rid of the optionality.  
… for DI proofs to be valuable, then need to have different features than existing systems (JOSE, COSE, X.509).  
… JCS could help in that regard..  
… We could separate different cryptosuites. Some with URDNA, some with JCS. Same crypto, but different canonicalization..  
… This shows the different options. The best we could to demonstrate value with those examples..  
… Whether or not those options take off isn't the point..  
… From a design perspective, it's important for data integrity to have distinctive value.  

**Dave Longley:** I agree with a lot of Orie. I also agree with Mike's comments about making decisions..  
… There are good arguments to be made that these algorithms don't do the same things. They make important choices.  
… I don't think suites MUST be able to support both, but its a good idea.  
… about making decisions and reusing tech. It's important to understand the design features..  

> *Orie Steele:* For the record I don't think a single suite should support both... I think a single suite MUST make a choice, so the implementation burden for the suite is minimized..

**Dave Longley:** we wouldn't be here if we thought JWTs and VCs are the same.  
… We spent a decade to get the VC work going forward because they do something different.  

> *Michael Prorock:* See [RFC8785](https://www.rfc-editor.org/rfc/rfc8785).

**Gabe Cohen:** I'm not against supporting JCS, but I'm curious about the arguments.  

**Michael Prorock:** To Gabe's question. Some of this goes to optionality. If we have extensibility, we should demonstrate choice.  
… But let's look at DI, it's about signing "the meaning".  
… The practical value I see is that signing with URDNA, that I'm signing the transformed NQuads..  
… If that meaning changes over time, that signature should break.  
… JCS doesn't get at that meaning..  
… To my mind, unless we can come up with the value of JCS, we should just get rid of the optionality.  
… But if we are going to keep optionality, JCS looks like the best candidate.  
… There have been so many times this has been attempted..  
… If you look at the XML stuff....  
… It's concerning to me to have the optionality unless we can state the value of it.  

**Manu Sporny:** I'm concerned we aren't going to get to the "easier" items. Can we put a pin in this and talk about proof chains..  
… also different about JWS2020 uniqueness would be good to discuss.  
… dequeing myself. Can we wrap this topic up?.  

> *Michael Prorock:* [https://www.ietf.org/standards/process/informational-vs-experimental/](https://www.ietf.org/standards/process/informational-vs-experimental/) diffs on standard track vs informational.

**Michael Jones:** problems with JCS. If you're not canonicalizing floating point numbers, it's easy..  
… Unicode might also be a challenge.  

> *Dave Longley:* JSON is UTF-8.

**Michael Jones:** From my point of view Unicode canonicalization is not something you'd do in a JSON scheme, you'd do it at application layer.  
… my preference if we had to choose would be JCS over URDNA.  

**David Waite:** building on Mike's comment. When you canonicalize, you're trying to deal with syntax. With XML, the rules were smarter than the developers.  
… these different systems need to give them their sense of the data and not just integrity.  
… one is outputing NQUADs, one is outputing JSON.  

> *Michael Prorock:* +1 dwaite.

**David Waite:** At the end of the process, they get different data.  

**Orie Steele:** in URDNA, when data type is JSON, JSON is used internally.  
… The other comment: what's the value of JCS?.  
… Why transform JSON into a hashable format?.  
… It's because the structure and syntax of JSON. If you want to sign something, if you're dealing with ordering, you get different hashes, so it matters where that happens..  
… The sidetree protocol (which `did:ion` uses) uses JCS because it uses hashes and we didn't want the storage layer to be hackable at the storage layer.  

> *Dave Longley:* +1 to Orie.

**Orie Steele:** Microsoft's ion implementation seems to be doing well (that's to godiddy.com lists).  
… JCS has a use when used for that purpose.  
… It's basically about that hashes..  

> *Dave Longley:* +1 to not letting overreaction culture in the security community dismiss valid and useful use cases and features.

**Orie Steele:** Saying that I like data structures that always hash to a different value... that doesn't make me super happy about JSON.  
… It shows up in these places where we have different signatures and you have do design around this possibility..  
… you BETTER think about that, because it is fundamental to JSON.  
… There are places you don't care because you're just signing over bytes. Or you might, because you're reconstructing options over time..  

</details>

**Comment by msporny** [comment]
PR has been raised to address this issue here: https://github.com/w3c/vc-di-eddsa/pull/26

**Comment by msporny** [comment]
PR #26 has been merged, closing.
